define l = Character('Ms Lalonde', color="#c8ffc8")              
define c = Character('Colette', color="#c8ffc8")
define r = Character('Roger', color="#c8ffc8")
define e = Character('Enzo', color="#c8ffc8")
define s = Character('Scylla', color="#c8ffc8")
define m = Character('Me', color="#c8ffc8")